services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_diw
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: abc123
      MONGO_INITDB_DATABASE: bbdd
    volumes:
      - mongodb_diw_data:/data/db

volumes:
  mongodb_diw_data:
    driver: local
